send_anonymous_usage_stats: false
dbt101:
    target: dev
    outputs:
        dev:
            account: '{{ env_var("DBT_KBC_DEV_ACCOUNT") }}'
            database: '{{ env_var("DBT_KBC_DEV_DATABASE") }}'
            password: '{{ env_var("DBT_KBC_DEV_PASSWORD") }}'
            schema: '{{ env_var("DBT_KBC_DEV_SCHEMA") }}'
            type: '{{ env_var("DBT_KBC_DEV_TYPE") }}'
            user: '{{ env_var("DBT_KBC_DEV_USER") }}'
            warehouse: '{{ env_var("DBT_KBC_DEV_WAREHOUSE") }}'
            threads: 4
